import { Injectable, NotFoundException } from "@nestjs/common";
import { prisma } from "@forge/database";
import type {
  CodexTask,
  ContextPackageResponse,
  GenerateContextPackageRequest,
  RepositorySnapshot,
} from "@forge/types";
import { toSnapshotDto } from "../shared/snapshotMapper.js";
import { renderArchitectureMermaid, renderDependencyTable } from "../shared/templates.js";
import { deriveArchitectureConstraints, deriveCodingStandards, deriveKnownIssues } from "./constraints.js";
import { selectRelevantFiles } from "./relevance.js";

@Injectable()
export class ContextPackageService {
  async getLatestSnapshot(projectId: string): Promise<RepositorySnapshot> {
    const snapshotRow = await prisma.repositorySnapshot.findFirst({
      where: { projectId },
      orderBy: { createdAt: "desc" },
    });
    if (!snapshotRow) {
      throw new NotFoundException(`No snapshot yet for project ${projectId} — analysis may still be running`);
    }
    return toSnapshotDto(snapshotRow);
  }

  renderArchitectureMd(snapshot: RepositorySnapshot): string {
    const constraints = deriveArchitectureConstraints(snapshot);
    return [
      "# Architecture",
      "",
      "## System diagram",
      renderArchitectureMermaid(snapshot),
      "",
      "## Constraints",
      constraints.length > 0 ? constraints.map((c) => `- ${c}`).join("\n") : "_None detected._",
      "",
      "## Dependencies",
      renderDependencyTable(snapshot),
    ].join("\n");
  }

  renderDatabaseMd(snapshot: RepositorySnapshot): string {
    const schemaFile = snapshot.referenceFiles.find((f) => f.path === "prisma/schema.prisma");
    if (schemaFile) {
      return ["# Database schema", "", "```prisma", schemaFile.content.trim(), "```"].join("\n");
    }
    const orm = snapshot.frameworks.find((f) => f.category === "orm");
    return [
      "# Database schema",
      "",
      orm
        ? `${orm.name} detected, but Forge doesn't yet extract raw schema content for this ORM (only \`prisma/schema.prisma\` is captured today — see docs/architecture.md).`
        : "_No ORM detected._",
    ].join("\n");
  }

  renderCodingStandardsMd(snapshot: RepositorySnapshot): string {
    const standards = deriveCodingStandards(snapshot);
    return [
      "# Coding standards",
      "",
      standards.length > 0 ? standards.map((s) => `- ${s}`).join("\n") : "_None detected._",
    ].join("\n");
  }

  renderKnownIssuesMd(snapshot: RepositorySnapshot): string {
    const issues = deriveKnownIssues(snapshot);
    return [
      "# Known issues",
      "",
      issues.length > 0 ? issues.map((i) => `- ⚠ ${i}`).join("\n") : "_None detected._",
    ].join("\n");
  }

  renderTaskMd(request: GenerateContextPackageRequest, relevantFiles: string[]): string {
    return [
      `# ${request.taskTitle}`,
      "",
      request.taskDescription,
      "",
      "## Requirements",
      (request.requirements ?? []).map((r) => `1. ${r}`).join("\n") || "_None specified._",
      "",
      "## Constraints",
      (request.constraints ?? []).map((c) => `- ${c}`).join("\n") || "_None specified._",
      "",
      "## Acceptance criteria",
      (request.acceptanceCriteria ?? []).map((a) => `- [ ] ${a}`).join("\n") || "_None specified._",
      "",
      "## Relevant files",
      relevantFiles.length > 0 ? relevantFiles.map((f) => `- \`${f}\``).join("\n") : "_None matched — provide file paths manually._",
    ].join("\n");
  }

  async generate(projectId: string, request: GenerateContextPackageRequest): Promise<ContextPackageResponse> {
    const snapshot = await this.getLatestSnapshot(projectId);
    const relevantFiles = selectRelevantFiles(snapshot, request.taskDescription);

    return {
      architectureMd: this.renderArchitectureMd(snapshot),
      databaseMd: this.renderDatabaseMd(snapshot),
      codingStandardsMd: this.renderCodingStandardsMd(snapshot),
      knownIssuesMd: this.renderKnownIssuesMd(snapshot),
      taskMd: this.renderTaskMd(request, relevantFiles),
      relevantFiles,
    };
  }

  async generateCursorRules(projectId: string): Promise<string> {
    const snapshot = await this.getLatestSnapshot(projectId);
    const architecture = deriveArchitectureConstraints(snapshot);
    const standards = deriveCodingStandards(snapshot);

    return [
      "# Generated by Forge — regenerated on architecture change, do not hand-edit sections below.",
      "",
      "## Architecture",
      ...architecture.map((c) => `- ${c}`),
      "",
      "## Coding standards",
      ...standards.map((s) => `- ${s}`),
      "",
      "## Testing",
      snapshot.testing.frameworks.length > 0
        ? `- All new logic requires tests using ${snapshot.testing.frameworks.join(", ")}.`
        : "- No test framework detected — flag this to the user rather than silently skipping tests.",
    ].join("\n");
  }

  async generateCodexTask(projectId: string, request: GenerateContextPackageRequest): Promise<CodexTask> {
    const snapshot = await this.getLatestSnapshot(projectId);
    const relevantFiles = selectRelevantFiles(snapshot, request.taskDescription);
    const architecture = deriveArchitectureConstraints(snapshot);

    return {
      task: request.taskTitle,
      context: {
        architecture: architecture.join(" "),
        files: relevantFiles,
        requirements: request.requirements ?? [],
        constraints: request.constraints ?? [],
      },
    };
  }
}
